package toolsdk

// Tool name constants identify each tool for AI model consumption.
const (
	ToolNameReportTask                  = "lattice_report_task"
	ToolNameGetAgent                    = "lattice_get_agent"
	ToolNameCreateAgent                 = "lattice_create_agent"
	ToolNameListAgents                  = "lattice_list_agents"
	ToolNameCreateAgentBuild            = "lattice_create_agent_build"
	ToolNameListTemplates               = "lattice_list_templates"
	ToolNameTemplateVersionParameters   = "lattice_template_version_parameters"
	ToolNameCreateTemplateVersion       = "lattice_create_template_version"
	ToolNameUpdateTemplateActiveVersion = "lattice_update_template_active_version"
	ToolNameCreateTemplate              = "lattice_create_template"
	ToolNameDeleteTemplate              = "lattice_delete_template"
	ToolNameUploadTarFile               = "lattice_upload_tar_file"
	ToolNameGetAuthenticatedUser        = "lattice_get_authenticated_user"
	ToolNameCreateTask                  = "lattice_create_task"
	ToolNameDeleteTask                  = "lattice_delete_task"
	ToolNameListTasks                   = "lattice_list_tasks"
	ToolNameGetTaskStatus               = "lattice_get_task_status"
	ToolNameSendTaskInput               = "lattice_send_task_input"
	ToolNameGetTaskLogs                 = "lattice_get_task_logs"
	ToolNameAgentBash                   = "lattice_agent_bash"
	ToolNameAgentLS                     = "lattice_agent_ls"
	ToolNameAgentReadFile               = "lattice_agent_read_file"
	ToolNameAgentWriteFile              = "lattice_agent_write_file"
	ToolNameAgentEditFile               = "lattice_agent_edit_file"
	ToolNameAgentEditFiles              = "lattice_agent_edit_files"
	ToolNameAgentPortForward            = "lattice_agent_port_forward"
	ToolNameAgentListApps               = "lattice_agent_list_apps"
	ToolNameGetAgentSidecarLogs         = "lattice_get_agent_sidecar_logs"
	ToolNameGetAgentBuildLogs           = "lattice_get_agent_build_logs"
	ToolNameGetTemplateVersionLogs      = "lattice_get_template_version_logs"
	ToolNameSearch                      = "search"
	ToolNameFetch                       = "fetch"
)
